version: "2.1"

services:
  messageBus:
    container_name: soa_messageBus
    image: "soa/bus"
    ports:
      - "5001:5000"
    expose:
      - "5001"

  orderService_database: # database for orderService
    container_name: soa_orderService_database
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=teama
      - MYSQL_DATABASE=uberoo
    expose:
      - "3306"
    healthcheck: # condition to consider the bd is ready
      test: 'mysqladmin ping --silent'

  orderService:
    container_name: soa_orderService
    image: "soa/wb/orderservice"
    ports:
      - "9555:8080"
    expose:
      - "9555"
    restart: always # if db is up too early, restart
    links: # for the hostname mapping
      - orderService_database 
      - messageBus
    depends_on:
      orderService_database: # wait for db to be up
        condition: service_healthy

  #coursierService:
  #  container_name: soa_coursierService
  #  image: "soa/wb/coursierservice"
  #  ports:
  #    - "9666:8080"
  #  expose:
  #    - "9666"
  #  restart: always # if db is up too early, restart
  #  depends_on:
  #    - messageBus
  #restaurantService:
  #  container_name: soa_restaurantService
  #  image: "soa/wb/restaurantservice"
  #  ports:
  #    - "9777:8080"
  #  expose:
  #    - "9777"
  #  restart: always # if db is up too early, restart
  #  depends_on:
  #    - messageBus

        