version: "2.1"

services:
  messageBus:
    image: "soa/bus"
    ports:
      - "5001:5000"
    expose:
      - "5001"

  orderService_database: # database for orderService
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=teama
      - MYSQL_DATABASE=uberoo
    expose:
      - "3306"
    healthcheck: # condition to consider the bd is ready
      test: 'mysqladmin ping --silent'

  orderService:
    image: "soa/wb/orderservice"
    ports:
      - "9555:8080"
    expose:
      - "9555"
    restart: always # if db is up too early, restart
    links: 
      - orderService_database # for the hostname mapping
    depends_on:
      orderService_database: # wait for db to be up
        condition: service_healthy