version: '3.3'

services:
  organiserClient:
    image: "soa/wb/orderservice"
    ports:
      - "9555:8080"
  messageBus:
    image: "soa/bus"
    ports:
      - "5000:5000"
  database:
    image: "soa/database"
    ports:
      - "3306:3306"
