version: '2.1'

services:
  messageBus:
    image: "soa/bus"
    ports:
      - "5001:5000"

  oS_database:
    image: "soa/database"
    ports:
      - "3307:3306"
    healthcheck:
      test: 'mysqladmin ping --silent'

  orderService:
    image: "soa/wb/orderservice"
    ports:
      - "9555:8080"
    depends_on:
      oS_database:
        condition: service_healthy