version: '3.3'

services:
  messageBus:
    image: "soa/bus"
    ports:
      - "5001:5000"

  database:
    image: "soa/database"
    ports:
      - "3307:3306"

  organiserClient:
    image: "soa/wb/orderservice"
    ports:
      - "9555:8080"
